# pdf_generator_v3_1.py
# Modern PDF Report Generator for AestheticSafe v3.1
# Based on NY Hospital CBC Report visual design
# Version: V3.1 — November 2025
# Multilingual support: EN/ES/PT/AR

from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.colors import HexColor
from reportlab.lib.utils import ImageReader
from datetime import datetime, timezone
import uuid
import qrcode
from PIL import Image
import io

# Color scheme (AestheticSafe official palette)
COLOR_LOW = HexColor("#38c694")      # Green - Low risk (official)
COLOR_MODERATE = HexColor("#fcb960")  # Yellow - Moderate risk (official)
COLOR_HIGH = HexColor("#fa5f45")      # Red - High risk (official)
COLOR_GRAY = HexColor("#E5E5E5")      # Background bar
COLOR_TEXT = HexColor("#333333")      # Dark gray text
COLOR_TEXT_LIGHT = HexColor("#777777")  # Light gray for footer
COLOR_TITLE = HexColor("#000000")     # Black for main titles

# ==========================================================
# 🌍 Multilingual Translation System
# ==========================================================

TRANSLATIONS = {
    "en": {
        "title": "AestheticSafe Risk Summary",
        "version": "— v3.1",
        "subtitle": "Predictive and Preventive Aesthetic Evaluation",
        "patient_info": "Patient Information",
        "name": "Name",
        "age": "Age",
        "years": "years",
        "height": "Height",
        "weight": "Weight",
        "report_id": "Report ID",
        "generated": "Generated",
        "clinical_metrics": "Clinical Metrics",
        "bmi_label": "Body Mass Index (BMI)",
        "bmi_normal_range": "Normal range: 18.5 - 24.9",
        "caprini_label": "Caprini VTE Risk Score",
        "caprini_normal_range": "Normal range: 0 - 2 (Low)",
        "overall_risk_label": "Overall Surgical Risk Factor",
        "overall_risk_target": "Target range: < 1.5 (Low)",
        "recommendations_title": "Clinical Recommendations",
        "recommendations_preview": "Full recommendations will be available in the complete report.",
        "recommendations_none": "No specific recommendations at this time.",
        "disclaimer_title": "Clinical Disclaimer",
        "disclaimer_text": (
            "This report was automatically generated by AestheticSafe® v3.1. "
            "The information is for guidance only and must be reviewed by a qualified physician "
            "before making any clinical decisions. It does not replace professional medical judgment."
        ),
        "footer": "© AestheticSafe® 2025 — Buenos Aires, Argentina — info@aestheticsafe.com",
        "verification_code": "Verification Code",
    },
    "es": {
        "title": "Informe de Riesgo AestheticSafe",
        "version": "— v3.1",
        "subtitle": "Evaluación Estética Predictiva y Preventiva",
        "patient_info": "Información del Paciente",
        "name": "Nombre",
        "age": "Edad",
        "years": "años",
        "height": "Altura",
        "weight": "Peso",
        "report_id": "ID del Informe",
        "generated": "Generado",
        "clinical_metrics": "Métricas Clínicas",
        "bmi_label": "Índice de Masa Corporal (IMC)",
        "bmi_normal_range": "Rango normal: 18.5 - 24.9",
        "caprini_label": "Puntuación de Riesgo VTE Caprini",
        "caprini_normal_range": "Rango normal: 0 - 2 (Bajo)",
        "overall_risk_label": "Factor de Riesgo Quirúrgico Global",
        "overall_risk_target": "Rango objetivo: < 1.5 (Bajo)",
        "recommendations_title": "Recomendaciones Clínicas",
        "recommendations_preview": "Las recomendaciones completas estarán disponibles en el informe completo.",
        "recommendations_none": "No hay recomendaciones específicas en este momento.",
        "disclaimer_title": "Descargo Clínico",
        "disclaimer_text": (
            "Este informe fue generado automáticamente por AestheticSafe® v3.1. "
            "La información tiene carácter orientativo y debe ser revisada por un médico calificado "
            "antes de tomar decisiones clínicas. No sustituye el juicio médico profesional."
        ),
        "footer": "© AestheticSafe® 2025 — Buenos Aires, Argentina — info@aestheticsafe.com",
        "verification_code": "Código de Verificación",
    },
    "pt": {
        "title": "Relatório de Risco AestheticSafe",
        "version": "— v3.1",
        "subtitle": "Avaliação Estética Preditiva e Preventiva",
        "patient_info": "Informações do Paciente",
        "name": "Nome",
        "age": "Idade",
        "years": "anos",
        "height": "Altura",
        "weight": "Peso",
        "report_id": "ID do Relatório",
        "generated": "Gerado",
        "clinical_metrics": "Métricas Clínicas",
        "bmi_label": "Índice de Massa Corporal (IMC)",
        "bmi_normal_range": "Faixa normal: 18.5 - 24.9",
        "caprini_label": "Pontuação de Risco VTE Caprini",
        "caprini_normal_range": "Faixa normal: 0 - 2 (Baixo)",
        "overall_risk_label": "Fator de Risco Cirúrgico Geral",
        "overall_risk_target": "Faixa alvo: < 1.5 (Baixo)",
        "recommendations_title": "Recomendações Clínicas",
        "recommendations_preview": "As recomendações completas estarão disponíveis no relatório completo.",
        "recommendations_none": "Sem recomendações específicas no momento.",
        "disclaimer_title": "Aviso Clínico",
        "disclaimer_text": (
            "Este relatório foi gerado automaticamente pelo AestheticSafe® v3.1. "
            "As informações têm caráter orientativo e devem ser revisadas por um médico qualificado "
            "antes de qualquer decisão clínica. Não substitui o julgamento médico profissional."
        ),
        "footer": "© AestheticSafe® 2025 — Buenos Aires, Argentina — info@aestheticsafe.com",
        "verification_code": "Código de Verificação",
    },
    "ar": {
        "title": "تقرير المخاطر من AestheticSafe",
        "version": "— الإصدار 3.1",
        "subtitle": "تقييم جمالي تنبؤي ووقائي",
        "patient_info": "معلومات المريض",
        "name": "الاسم",
        "age": "العمر",
        "years": "سنوات",
        "height": "الطول",
        "weight": "الوزن",
        "report_id": "معرّف التقرير",
        "generated": "تم الإنشاء",
        "clinical_metrics": "المقاييس السريرية",
        "bmi_label": "مؤشر كتلة الجسم (BMI)",
        "bmi_normal_range": "النطاق الطبيعي: 18.5 - 24.9",
        "caprini_label": "درجة خطر الجلطة الوريدية (كابريني)",
        "caprini_normal_range": "النطاق الطبيعي: 0 - 2 (منخفض)",
        "overall_risk_label": "عامل الخطر الجراحي الإجمالي",
        "overall_risk_target": "النطاق المستهدف: < 1.5 (منخفض)",
        "recommendations_title": "التوصيات السريرية",
        "recommendations_preview": "ستتوفر التوصيات الكاملة في التقرير الكامل.",
        "recommendations_none": "لا توجد توصيات محددة في الوقت الحالي.",
        "disclaimer_title": "إخلاء المسؤولية الطبية",
        "disclaimer_text": (
            "تم إنشاء هذا التقرير تلقائيًا بواسطة AestheticSafe® v3.1. "
            "المعلومات لأغراض توجيهية فقط ويجب مراجعتها من قبل طبيب مؤهل "
            "قبل اتخاذ أي قرارات سريرية. لا يحل محل الحكم الطبي المهني."
        ),
        "footer": "© AestheticSafe® 2025 — بوينس آيرس، الأرجنتين — info@aestheticsafe.com",
        "verification_code": "رمز التحقق",
    },
}


def translate_label(key: str, lang: str = "en") -> str:
    """Safe translation lookup with fallback to English."""
    lang = (lang or "en").lower()
    # Handle locale variants (e.g., "es-AR" -> "es")
    if lang not in TRANSLATIONS:
        lang = lang.split("-")[0]
    return TRANSLATIONS.get(lang, TRANSLATIONS["en"]).get(key, key)


def draw_horizontal_bar(c, x, y, width, value, min_val, max_val, risk_level):
    """
    Draw a horizontal bar similar to NY hospital report.
    
    Args:
        c: ReportLab canvas
        x, y: Position
        width: Total bar width
        value: Current value
        min_val: Minimum of normal range
        max_val: Maximum of normal range
        risk_level: "low", "moderate", or "high"
    """
    bar_height = 8
    
    # Background bar (gray)
    c.setFillColor(COLOR_GRAY)
    c.rect(x, y - bar_height, width, bar_height, fill=1, stroke=0)
    
    # Calculate position of value marker
    try:
        value_pos = (float(value) - min_val) / (max_val - min_val)
        value_pos = max(0, min(1, value_pos))  # Clamp to 0-1
    except (ValueError, ZeroDivisionError):
        value_pos = 0.5
    
    # Colored section (from start to value)
    color = COLOR_LOW if risk_level == "low" else COLOR_MODERATE if risk_level == "moderate" else COLOR_HIGH
    c.setFillColor(color)
    c.rect(x, y - bar_height, width * value_pos, bar_height, fill=1, stroke=0)
    
    # Value marker (small circle)
    marker_x = x + (width * value_pos)
    c.setFillColor(HexColor("#000000"))
    c.circle(marker_x, y - bar_height/2, 4, fill=1, stroke=0)


def generar_pdf_v3_1(datos: dict, *, preview: bool = False, full: bool = False, lang: str | None = None) -> tuple[bytes, str]:
    """
    Generate modern medical-grade PDF report v3.1 with QR code verification.
    Based on NY Hospital CBC report visual design.
    Multilingual: EN/ES/PT/AR
    
    Returns:
        tuple: (pdf_bytes, verification_uuid)
    """
    
    # Generate unique verification UUID
    verification_uuid = str(uuid.uuid4())
    
    # Setup
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    W, H = A4
    ML, MR, MT, MB = 2.5 * cm, 2.5 * cm, 2.0 * cm, 2.0 * cm
    y = H - MT
    
    # Language setup - normalize to lowercase
    user_lang = (lang if lang is not None else "es").lower()
    
    # Extract data
    rep_id = datos.get("rep_id") or f"ASTH-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}"
    paciente = datos.get("paciente", {}) or {}
    nombre = paciente.get("nombre", "—")
    edad = paciente.get("edad", "")
    altura_cm = paciente.get("altura_cm", "")
    peso_kg = paciente.get("peso_kg", "")
    bmi_raw = datos.get("bmi", "")
    cap_score_raw = datos.get("caprini_score", "")
    cap_cat = datos.get("caprini_categoria", "")
    factor_raw = datos.get("factor_riesgo", datos.get("factor", ""))
    nivel = datos.get("nivel_riesgo", datos.get("nivel", ""))
    recs = datos.get("recomendaciones", [])
    
    if isinstance(recs, str):
        recs = [r.strip() for r in recs.split("\n") if r.strip()]
    
    # Safe type conversion for numeric values
    def safe_float(value, default=0.0):
        try:
            return float(value) if value not in ("", None) else default
        except (ValueError, TypeError):
            return default
    
    def safe_int(value, default=0):
        try:
            return int(float(value)) if value not in ("", None) else default
        except (ValueError, TypeError):
            return default
    
    # Convert to numeric types for comparisons
    bmi = safe_float(bmi_raw)
    cap_score = safe_int(cap_score_raw)
    factor = safe_float(factor_raw)
    
    # Determine risk levels for colors
    bmi_risk = "low" if bmi < 25 else "moderate" if bmi < 30 else "high" if bmi > 0 else "low"
    caprini_risk = "low" if cap_score <= 2 else "moderate" if cap_score <= 8 else "high" if cap_score > 0 else "low"
    
    # ===== QR CODE (Top Right Corner) =====
    qr_size = 2.2 * cm  # QR code size
    qr_x = W - MR - qr_size
    qr_y = H - MT - qr_size
    
    # Generate QR code with verification URL
    verification_url = f"https://app.aestheticsafe.com/verify?id={verification_uuid}"
    qr = qrcode.QRCode(version=1, box_size=10, border=1)
    qr.add_data(verification_url)
    qr.make(fit=True)
    qr_img = qr.make_image(fill_color="black", back_color="white")
    
    # Convert PIL image to ReportLab image
    qr_buffer = io.BytesIO()
    qr_img.save(qr_buffer, format='PNG')
    qr_buffer.seek(0)
    
    # Draw QR code on PDF
    c.drawImage(ImageReader(qr_buffer), qr_x, qr_y, width=qr_size, height=qr_size)
    
    # QR label below the code
    c.setFont("Helvetica", 7)
    c.setFillColor(HexColor("#666666"))
    c.drawCentredString(qr_x + qr_size/2, qr_y - 10, "Scan to verify")
    
    # ===== HEADER =====
    y -= 15
    
    # Title (BLACK - official AestheticSafe style)
    c.setFillColor(COLOR_TITLE)
    c.setFont("Helvetica-Bold", 18)
    title_text = translate_label("title", user_lang)
    c.drawString(ML, y, title_text)
    
    # Version on the right side of the page
    c.setFont("Helvetica", 10)
    c.setFillColor(HexColor("#666666"))
    c.drawRightString(W - MR, y, translate_label("version", user_lang))
    y -= 18
    
    # Subtitle (Dark gray, light weight for elegance)
    c.setFillColor(HexColor("#666666"))
    c.setFont("Helvetica", 13)
    c.drawString(ML, y, translate_label("subtitle", user_lang))
    y -= 25
    
    # Thin separator line
    c.setStrokeColor(COLOR_GRAY)
    c.setLineWidth(0.5)
    c.line(ML, y, W - MR, y)
    y -= 20
    
    # ===== PATIENT INFO (Compact) =====
    c.setFillColor(COLOR_TEXT)
    c.setFont("Helvetica-Bold", 10)
    c.drawString(ML, y, translate_label("patient_info", user_lang))
    y -= 15
    
    c.setFont("Helvetica", 9)
    info_line = f"{translate_label('name', user_lang)}: {nombre}"
    if edad: info_line += f"  •  {translate_label('age', user_lang)}: {edad} {translate_label('years', user_lang)}"
    if altura_cm and peso_kg: 
        info_line += f"  •  {translate_label('height', user_lang)}: {altura_cm} cm  •  {translate_label('weight', user_lang)}: {peso_kg} kg"
    c.drawString(ML, y, info_line)
    y -= 12
    
    c.setFont("Helvetica", 8)
    c.setFillColor(HexColor("#666666"))
    c.drawString(ML, y, f"{translate_label('report_id', user_lang)}: {rep_id}  •  {translate_label('generated', user_lang)}: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    y -= 25
    
    # ===== CLINICAL METRICS =====
    c.setFillColor(COLOR_TEXT)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(ML, y, translate_label("clinical_metrics", user_lang))
    y -= 20
    
    # BMI Score
    if bmi > 0:
        c.setFont("Helvetica-Bold", 10)
        c.setFillColor(COLOR_TEXT)
        c.drawString(ML, y, translate_label("bmi_label", user_lang))
        y -= 12
        
        c.setFont("Helvetica", 8)
        c.setFillColor(HexColor("#666666"))
        c.drawString(ML, y, translate_label("bmi_normal_range", user_lang))
        y -= 4
        
        # Bar
        bar_width = W - ML - MR - 100
        draw_horizontal_bar(c, ML, y, bar_width, bmi, 18.5, 35, bmi_risk)
        y -= 12
        
        # Value on right
        c.setFont("Helvetica-Bold", 14)
        c.setFillColor(COLOR_LOW if bmi_risk == "low" else COLOR_MODERATE if bmi_risk == "moderate" else COLOR_HIGH)
        c.drawRightString(W - MR, y + 8, f"{bmi:.1f}")
        y -= 18
    
    # Caprini Score
    if cap_score_raw not in ("", None):
        c.setFont("Helvetica-Bold", 10)
        c.setFillColor(COLOR_TEXT)
        c.drawString(ML, y, translate_label("caprini_label", user_lang))
        y -= 12
        
        c.setFont("Helvetica", 8)
        c.setFillColor(HexColor("#666666"))
        c.drawString(ML, y, translate_label("caprini_normal_range", user_lang))
        y -= 4
        
        # Bar
        bar_width = W - ML - MR - 100
        draw_horizontal_bar(c, ML, y, bar_width, cap_score, 0, 10, caprini_risk)
        y -= 12
        
        # Value and category
        c.setFont("Helvetica-Bold", 14)
        c.setFillColor(COLOR_LOW if caprini_risk == "low" else COLOR_MODERATE if caprini_risk == "moderate" else COLOR_HIGH)
        c.drawRightString(W - MR, y + 8, str(cap_score))
        
        if cap_cat:
            c.setFont("Helvetica", 8)
            c.setFillColor(HexColor("#666666"))
            c.drawRightString(W - MR, y - 2, f"({cap_cat})")
        y -= 18
    
    # Overall Risk Factor
    if factor > 0:
        c.setFont("Helvetica-Bold", 10)
        c.setFillColor(COLOR_TEXT)
        c.drawString(ML, y, translate_label("overall_risk_label", user_lang))
        y -= 12
        
        c.setFont("Helvetica", 8)
        c.setFillColor(HexColor("#666666"))
        c.drawString(ML, y, translate_label("overall_risk_target", user_lang))
        y -= 4
        
        # Determine risk level
        factor_risk = "low" if factor < 1.5 else "moderate" if factor < 3 else "high"
        
        bar_width = W - ML - MR - 100
        draw_horizontal_bar(c, ML, y, bar_width, factor, 0, 5, factor_risk)
        y -= 12
        
        # Value and level
        c.setFont("Helvetica-Bold", 14)
        c.setFillColor(COLOR_LOW if factor_risk == "low" else COLOR_MODERATE if factor_risk == "moderate" else COLOR_HIGH)
        c.drawRightString(W - MR, y + 8, f"{factor:.2f}")
        
        if nivel:
            c.setFont("Helvetica", 8)
            c.setFillColor(HexColor("#666666"))
            c.drawRightString(W - MR, y - 2, f"({nivel})")
        y -= 25
    
    # Separator
    c.setStrokeColor(COLOR_GRAY)
    c.setLineWidth(0.5)
    c.line(ML, y, W - MR, y)
    y -= 20
    
    # ===== RECOMMENDATIONS =====
    c.setFillColor(COLOR_TEXT)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(ML, y, translate_label("recommendations_title", user_lang))
    y -= 15
    
    if preview and not full:
        c.setFont("Helvetica-Oblique", 9)
        c.setFillColor(HexColor("#666666"))
        c.drawString(ML, y, translate_label("recommendations_preview", user_lang))
        y -= 20
    elif recs:
        c.setFont("Helvetica", 9)
        c.setFillColor(COLOR_TEXT)
        for rec in recs:
            # Bullet point
            c.circle(ML + 3, y - 3, 1.5, fill=1, stroke=0)
            
            # Text wrapping (simple)
            words = rec.split()
            line = []
            max_width = 85
            
            for word in words:
                test = " ".join(line + [word])
                if len(test) <= max_width:
                    line.append(word)
                else:
                    if line:
                        c.drawString(ML + 10, y, " ".join(line))
                        y -= 12
                        line = [word]
            if line:
                c.drawString(ML + 10, y, " ".join(line))
                y -= 12
            y -= 3
    else:
        c.setFont("Helvetica", 9)
        c.setFillColor(HexColor("#666666"))
        c.drawString(ML, y, translate_label("recommendations_none", user_lang))
        y -= 20
    
    y -= 10
    
    # ===== DISCLAIMER =====
    c.setStrokeColor(COLOR_GRAY)
    c.setLineWidth(0.5)
    c.line(ML, y, W - MR, y)
    y -= 15
    
    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(COLOR_TEXT)
    c.drawString(ML, y, translate_label("disclaimer_title", user_lang))
    y -= 12
    
    c.setFont("Helvetica", 8)
    c.setFillColor(HexColor("#666666"))
    disclaimer = translate_label("disclaimer_text", user_lang)
    
    # Wrap disclaimer text
    words = disclaimer.split()
    line = []
    max_width = 100
    for word in words:
        test = " ".join(line + [word])
        if len(test) <= max_width:
            line.append(word)
        else:
            c.drawString(ML, y, " ".join(line))
            y -= 10
            line = [word]
    if line:
        c.drawString(ML, y, " ".join(line))
    
    # Verification code (below disclaimer) - use generated UUID
    y -= 15
    c.setFont("Helvetica", 8)
    c.setFillColor(HexColor("#666666"))
    c.drawString(ML, y, f"{translate_label('verification_code', user_lang)}: {verification_uuid[:16].upper()}")
    
    # ===== FOOTER (Two lines, centered) =====
    c.setFont("Helvetica", 8)
    c.setFillColor(HexColor("#555555"))
    c.drawCentredString(W / 2, MB + 20, "Generated automatically by AestheticSafe® v3.1")
    c.drawCentredString(W / 2, MB + 10, "Bukret Pesce SB SRL — © AestheticSafe® 2025 — Buenos Aires, Argentina — info@aestheticsafe.com")
    
    # Close PDF
    c.showPage()
    c.save()
    buf.seek(0)
    return buf.getvalue(), verification_uuid
